# Generated by Django 3.1.3 on 2020-12-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palliatives', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
